name: "Workflow: Deployment using Container"
on:
  workflow_dispatch:
  push:
    branches:
      - containers

env: # WORKFLOW SPECEFIC ENV VARIABLES
  MONGODB_DB_NAME: "Github-actions-demo-db"
  CACHE_KEY: node-deps
jobs:
  job__test:
    environment: "UAT"
    env: # JOB SPECEFIC ENV VARIBALES
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: "cluster0.4wifdch.mongodb.net"
      MONGODB_USERNAME: "${{ secrets.MONGODB_SECRET_USERNAME }}"
      MONGODB_PASSWORD: "${{ secrets.MONGODB_SECRET_PASSWORD }}"
      PORT: "8080"
    runs-on: ubuntu-latest
    steps:
      - name: "Step: Clone Code"
        uses: actions/checkout@v3
      - name: "Step: Cache dependencies"
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{env.CACHE_KEY}}-${{ hashFiles('**/package-lock.json') }}
      - name: "Step: Install dependencies"
        run: npm ci
      - name: "Step: Run server"
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: "Step: Run tests"
        run: npm test
      - name: "Step: Output information"
        run: |
          echo "DB User: $MONGODB_USERNAME",
          echo "DB User: ${{ env.MONGODB_USERNAME }}",
  job__deploy:
    needs: job__test
    runs-on: ubuntu-latest
    steps:
      - name: "Step: Output information"
        # WORKFLOW SPECEFIC ENV VARIABLES are accessible but JOB SPECEFIC ENV VARIABLES are inaccessible out of that job scope
        run: |
          echo "DB (Available): $MONGODB_DB_NAME",
          echo "DB (Available): ${{ env.MONGODB_DB_NAME }}",
          echo "DB User (Unvailable): Out of the job scope ENV VAR Called: $MONGODB_USERNAME",
          echo "DB User (Unvailable): Out of the job scope ENV VAR Called: ${{ env.MONGODB_USERNAME }}",
