name: "Matrix demo wrokflow"
on:
  push:
    branches:
      - matrices
  workflow_dispatch:
jobs:
  job__build:
    continue-on-error: true
    strategy:
      matrix:
        operating_systems: [ "ubuntu-latest", "windows-latest" ]
        node_versions: [ 14, 16, 18]
    runs-on: ${{ matrix.operating_systems }}
    steps:
      - name: "Step: Get Code"
        uses: actions/checkout@v3
      - name: "Step: Install Node JS v${{ matrix.node_versions }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_versions }}
      - name: "Step: Install NODE_MODULES"
        run: npm ci
      - name: "Step: Build Project"
        run: npm run build

