name: "Matrix demo workflow"
on:
  push:
    branches:
      - matrices
  workflow_dispatch:
jobs:
  job__build:
    continue-on-error: true
    strategy:
      matrix:
        operating_systems: [ "ubuntu-latest", "windows-latest" ]
        node_versions: [ 12, 14, 16 ]
        exclude:
          - node_versions: 12
        include:
          # - node_versions: [18, 20] // this doesnt work
          - node_versions: 18
            operating_systems: "ubuntu-latest"
          - node_versions: 20
            operating_systems: "ubuntu-latest"
    runs-on: ${{ matrix.operating_systems }}
    steps:
      - name: "Step: Get Code"
        uses: actions/checkout@v3
      - name: "Step: Install Node JS v${{ matrix.node_versions }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_versions }}
      - name: "Step: Install NODE_MODULES"
        run: npm ci
      - name: "Step: Build Project"
        run: npm run build

